CREATE DATABASE SCREENTIME;
USE SCREENTIME;


CREATE TABLE screen_use_daily(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DAY TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME FLOAT NOT NULL
);